import type { Metadata } from 'next'
import { Jura, Lexend_Deca, Lexend_Exa } from 'next/font/google'
import './globals.css'
import LayoutProvider from '@/app/LayoutProvider'
import 'material-icons/iconfont/material-icons.css'
import '@radix-ui/themes/styles.css'

const lexendExa = Lexend_Exa({
  preload: true,
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-lexend-exa',
})
const jura = Jura({
  preload: true,
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-jura',
})
const lexendDeca = Lexend_Deca({
  preload: true,
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  variable: '--font-lexend-deca',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${jura.variable} ${lexendExa.variable} ${lexendDeca.variable} min-h-screen`}>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
