import type { Metadata } from "next"
import { Jura, Lexend_Deca, Lexend_Exa, Prompt } from "next/font/google"
import "./globals.css"
import LayoutProvider from "@/app/LayoutProvider"
import "material-icons/iconfont/material-icons.css"
import "@radix-ui/themes/styles.css"

const prompt = Prompt({
  preload: true,
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["thai", "latin"],
  variable: "--font-prompt"
})

// const lexendExa = Lexend_Exa({
//   preload: true,
//   weight: ['200', '300', '400', '500', '600', '700', '800'],
//   subsets: ['latin'],
//   variable: '--font-lexend-exa',
// })
// const jura = Jura({
//   preload: true,
//   weight: ['300', '400', '500', '600', '700'],
//   subsets: ['latin'],
//   variable: '--font-jura',
// })
// const lexendDeca = Lexend_Deca({
//   preload: true,
//   weight: ['300', '400', '500'],
//   subsets: ['latin'],
//   variable: '--font-lexend-deca',
// })

export const metadata: Metadata = {
  title: "Same Way",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        // ${jura.variable} ${lexendExa.variable} ${lexendDeca.variable}
        className={`${prompt.className} min-h-screen`}
      >
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
